# Generated by Django 6.1 on 2026-09-03 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=8)),
                ('program', models.CharField(max_length=64)),
                ('data_type', models.CharField(choices=[('registration', 'Registration'), ('enrollment', 'Enrollment'), ('distributions', 'Distributions'), ('household_survey', 'Household surveys'), ('geomapping_survey', 'Geomapping surveys'), ('impact_survey', 'Impact surveys'), ('buyback', 'Buyback / purchases'), ('loans', 'Loans'), ('payments', 'Payments / repayments'), ('staff', 'Staff'), ('other', 'Other')], max_length=32)),
                ('entity', models.CharField(choices=[('client', 'Client'), ('location', 'Location'), ('product', 'Product'), ('sale', 'Sale'), ('purchase', 'Purchase (buyback)'), ('loan', 'Loan'), ('payment', 'Payment'), ('people', 'People (staff)')], max_length=32)),
                ('operational_year', models.CharField(blank=True, max_length=16)),
                ('season', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('source_columns', models.JSONField(default=list)),
                ('column_mapping', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft — uploaded, not yet mapped'), ('mapped', 'Mapped — columns mapped, not yet committed'), ('saved', 'Saved — rows committed')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('mapped_data', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(default=list)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='bulk_uploader.uploadeddataset')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
