# Generated by Django 6.1 on 2026-09-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedrow',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='uploadeddataset',
            name='data_type',
            field=models.CharField(blank=True, choices=[('registration', 'Registration'), ('enrollment', 'Enrollment'), ('distributions', 'Distributions'), ('household_survey', 'Household surveys'), ('geomapping_survey', 'Geomapping surveys'), ('impact_survey', 'Impact surveys'), ('buyback', 'Buyback / purchases'), ('loans', 'Loans'), ('payments', 'Payments / repayments'), ('staff', 'Staff'), ('other', 'Other')], max_length=32),
        ),
    ]
