# Generated by Django 6.1 on 2026-09-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_uploader', '0002_uploadedrow_raw_data_alter_uploadeddataset_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddataset',
            name='ignored_columns',
            field=models.JSONField(default=list),
        ),
    ]
