# Generated by Django 6.1 on 2026-09-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_uploader', '0003_uploadeddataset_ignored_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddataset',
            name='location_type',
            field=models.CharField(blank=True, choices=[('Nursery', 'Nursery'), ('Site', 'Site'), ('Shop', 'Shop'), ('Warehouse', 'Warehouse'), ('Online', 'Online'), ('Other', 'Other')], max_length=16),
        ),
    ]
