# Generated by Django 6.1 on 2026-09-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_role_rules'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleassignmentrule',
            name='group',
        ),
        migrations.AddField(
            model_name='roleassignmentrule',
            name='groups',
            field=models.ManyToManyField(related_name='role_assignment_rules', to='auth.group'),
        ),
    ]
