# Generated by Django 6.1 on 2026-09-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reseed_role_rules_with_groups_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='wimbiprofile',
            name='department_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='wimbiprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
