"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Comma-separated in production (the ALB's DNS name / a real domain, once
# one exists) — see aws_migration.md. Defaults preserve local dev exactly.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'corsheaders',
    'django_htmx',
    'accounts',
    'analytics_mirror',
    'farmers',
    'bulk_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # In-process static file serving — no S3/CloudFront needed at this
    # traffic level (aws_migration.md). Harmless locally: falls through to
    # STATIC_ROOT, which is only populated after collectstatic runs.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.session_user',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Deliberately no custom search_path here. An earlier version put
# analytics_mirror ahead of public — which meant Django's OWN migrated
# tables (auth, sessions, admin) landed inside analytics_mirror instead of
# public, since CREATE TABLE without a schema qualifier always targets the
# first schema on the search_path. A later `DROP SCHEMA analytics_mirror
# CASCADE` (done to reset the mirror's shape) silently wiped django_session
# and friends along with it. Fix: the analytics_mirror app's unmanaged
# models schema-qualify their own db_table directly (see
# analytics_mirror/models.py) — Django's own tables stay in the normal
# default `public` schema, completely unaffected by whatever happens to
# analytics_mirror.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['POSTGRES_DB'],
        'USER': os.environ['POSTGRES_USER'],
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'HOST': os.environ['POSTGRES_HOST'],
        'PORT': os.environ['POSTGRES_PORT'],
    }
}

REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')


# CORS / sessions — Reflex (its own dev server, typically :3000) calls this
# API (:8000) as a separate origin. Credentials (session cookie) must be
# explicitly allowed both sides: CORS_ALLOW_CREDENTIALS here, and
# `credentials: "include"` on every fetch from the Reflex app.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SAMESITE = 'Lax'

REST_FRAMEWORK = {
    # Without a session authenticator here, DRF's own (empty) auth
    # resolution silently overwrites request._request.user back to
    # AnonymousUser on every @api_view call — see accounts/authentication.py.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.CsrfExemptSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [],
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Auth
# https://docs.djangoproject.com/en/6.1/ref/settings/#login-url

LOGIN_URL = 'login_page'


# HTTPS — off by default so this stays correct for both local dev (plain
# HTTP) and the AWS ALB's first apply (HTTP-only until a domain + ACM cert
# exist, see infra/aws/README.md). Flip DJANGO_HTTPS=True once the ALB has
# a real TLS listener — turning this on before that exists would redirect
# every request into a loop, since there'd be nothing terminating TLS yet.
DJANGO_HTTPS = os.environ.get('DJANGO_HTTPS', 'False') == 'True'
SECURE_SSL_REDIRECT = DJANGO_HTTPS
SESSION_COOKIE_SECURE = DJANGO_HTTPS
CSRF_COOKIE_SECURE = DJANGO_HTTPS
SECURE_HSTS_SECONDS = 31536000 if DJANGO_HTTPS else 0


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
